# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # keep your service names short
    app.twig.app_extension:
        class: AppBundle\Twig\Extension\AppExtension
        tags:
            - { name: twig.extension }
            
    app.twig.extension:
        class: AppBundle\Twig\Extension\PaginationExtension
        arguments: [@knp_paginator.helper.processor]
        tags:
        - { name: twig.extension }
        
    app.twig.controller_action_extension:
        class: AppBundle\Twig\Extension\ControllerActionExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }
        
    app.form.icon_button_extension:
        class: AppBundle\Form\Extension\IconButtonExtension
        tags:
            - { name: form.type_extension, alias: button }    
            
    app.odbc_driver:
        class: AppBundle\Utils\Driver
        arguments: ["VOS", "dba", "lucas"]
        calls:
            - [db_connect]
            
    app.rest_api:
        class: AppBundle\Utils\RestAPI
        arguments: ["@service_container"]
        
    model.provenance:
        class: AppBundle\Model\Provenance
        arguments: ["@app.rest_api"]
        
    model.wro:
        class: AppBundle\Model\WRO
        arguments: [@app.rest_api, @service_container]
        
    model.search:
        class: AppBundle\Model\Search
        arguments: ["@app.rest_api"]
        
    model.workflow:
        class: AppBundle\Model\Workflow
        arguments: [@app.rest_api, @service_container]
        
    model.annotation:
        class: AppBundle\Model\Annotation
        arguments: ["@app.rest_api"]   
        
    model.qualitydimension:
        class: AppBundle\Model\QualityDimension
        arguments: ["@app.rest_api"] 
        
    model.qualitymetric:
        class: AppBundle\Model\QualityMetric
        arguments: ["@app.rest_api"] 
        
    model.security:
        class: AppBundle\Model\Security
        arguments: [@app.rest_api, @service_container] 
        
    model.scriptconverter:
        class: AppBundle\Model\ScriptConverterModel
        arguments: [@service_container]
    
    dao.scriptconverter:
        class: AppBundle\Dao\ScriptConverterDAO
        arguments: [@app.rest_api, @service_container]
                    
    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [ @service_container ]
        
    authentication_handler:
        class: AppBundle\Security\AuthenticationHandler
        calls:
            - [ setContainer, [ @service_container ] ]        