# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # keep your service names short
    app.twig.app_extension:
        class: AppBundle\Twig\Extension\AppExtension
        tags:
            - { name: twig.extension }
            
    app.odbc_driver:
        class: AppBundle\Utils\Driver
        arguments: ["VOS", "dba", "lucas"]
        calls:
            - [db_connect]
    model.provenance:
        class: AppBundle\Model\Provenance
        arguments: ["@app.odbc_driver"]
        
    model.workflow:
        class: AppBundle\Model\Workflow
        arguments: ["@doctrine.orm.default_entity_manager","@app.odbc_driver"]
        
    model.annotation:
        class: AppBundle\Model\Annotation
        arguments: ["@app.odbc_driver"]          
        
    model.yesworkflow:
        class: AppBundle\Model\YesWorkflow