AppBundle\Entity\InputRun: 
    type: entity
    fields:   
        uri:
            type: string
        content:
            type: string
    manyToOne:
        process_run:
            targetEntity: ProcessRun
            inversedBy: inputs
        workflow_run:
            targetEntity: WorkflowRun
            inversedBy: inputs