AppBundle\Entity\InputRun: 
    type: entity
    fields:   
        uri:
            type: string
        content:
            type: string
    manyToOne:
        process:
            targetEntity: ProcessRun
            inversedBy: inputs