AppBundle\Entity\Input: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string
        label:
            type: string
        example_data:
            type: string
    manyToOne:
        process:
            targetEntity: Process
        workflow:
            targetEntity: Workflow
