AppBundle\Entity\OutputRun: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        content:
            type: string
    manyToOne:
        process_run:
            targetEntity: ProcessRun
            inversedBy: outputs
        workflow_run:
            targetEntity: WorkflowRun
            inversedBy: outputs
        output:
            targetEntity: Output
            inversedBy: outputs_run
    oneToMany:
        quality_annotation:
            targetEntity: QualityAnnotation
            mappedBy: output_run