AppBundle\Entity\Output: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string
        label:
            type: string
        example_data:
            type: string
    manyToOne:
        process:
            targetEntity: Process
            inversedBy: outputs
        workflow:
            targetEntity: Workflow
            inversedBy: outputs
        output:
            targetEntity: Output
            inversedBy: outputs_run