AppBundle\Entity\Person: 
    type: entity
    fields:   
        uri:
            type: string
        name:
            type: string
        email:
            type: string
        password:
            type: string
        homepage:
            type: string
        organization:
            type: string
        roles:
            type: string
        salt:
            type: string
        description:
            type: text
        country:
            type: string
        state:
            type: string
        city:
            type: string        
        created_at:
            type: string
        updated_at:
            type: string
