AppBundle\Entity\Process: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string
        label:
            type: string
    manyToOne:
        workflow:
            targetEntity: Workflow
            inversedBy: processes
    oneToMany:
        process_runs:
            targetEntity: ProcessRun
            mappedBy: process
        outputs:
            targetEntity: Output
            mappedBy: process
        inputs:
            targetEntity: Input
            mappedBy: process