AppBundle\Entity\ProcessRun: 
    type: entity
    fields:  
        uri:
            type: string        
        label:
            type: string
        started_at_time:
            type: datetime
        ended_at_time:
            type: datetime
    manyToOne:
        workflow_run:
            targetEntity: WorkflowRun
            inversedBy: processes_run
        process:
            targetEntity: Process
            inversedBy: processes_run
    oneToMany:
        outputs_run:
            targetEntity: OutputRun
            mappedBy: process_run
        inputs_run:
            targetEntity: InputRun
            mappedBy: process_run
        quality_annotation:
            targetEntity: QualityAnnotation
            mappedBy: process_run