AppBundle\Entity\QualityDimension: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        name:
            type: string
        description:
            type: string
        valueType:
            type: string
        creator:
            type: string
    oneToMany:
        quality_annotation:
            targetEntity: QualityAnnotation
            mappedBy: quality_dimension
        quality_metric:
            targetEntity: QualityMetric
            mappedBy: quality_dimension