AppBundle\Entity\QualityMetric: 
    type: entity    
    id:
        uri:
            type: string
    fields: 
        metric:
            type: string
        description:
            type: string
        result:
            type: string
        creator:
            type: string
    manyToOne:
        quality_dimension:
            targetEntity: QualityDimension
            inversedBy: quality_metrics