AppBundle\Entity\QualityAnnotation: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        value:
            type: string
        created_at_time:
            type: datetime
        type:
            type: string
        element_uri:
            type: string
        creator:
            type: string
    oneToOne:
        quality_metric_annotation:
            targetEntity: QualityMetricAnnotation
    manyToOne:
        quality_dimension:
            targetEntity: QualityDimension
            inversedBy: quality_annotation
        workflow:
            targetEntity: Workflow
            inversedBy: quality_annotation
        process_run:
            targetEntity: ProcessRun
            inversedBy: quality_annotation
        output_run:
            targetEntity: OutputRun
            inversedBy: quality_annotation