AppBundle\Entity\QualityMetricAnnotation: 
    type: entity    
    id:
        uri:
            type: string
    fields: 
        result:
            type: string
    manyToOne:
        quality_metric:
            targetEntity: QualityMetric