AppBundle\Entity\ScriptConverter: 
    type: entity
    fields: 
        uri:
            type: string
        description:
            type: string
        title:
            type: string
        hash:
            type: string
        script_language:
            type: string
        created_at:
            type: datetime
        updated_at:
            type: datetime
        
    oneToOne:
        ro:
            targetEntity: ResearchObject
    oneToMany:
        workflows:
            targetEntity: Workflow
            mappedBy: scriptConversion
    manyToOne:
        creator:
            targetEntity: Person  