AppBundle\Entity\ScriptConverter: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string
        title:
            type: string
        hash:
            type: string
        script_language:
            type: string
        graph_properties:
            type: string
        created_at:
            type: datetime
        updated_at:
            type: datetime
        
    oneToOne:
        wro:
            targetEntity: WRO
        workflow:
            targetEntity: Workflow
    oneToMany:
        workflows:
            targetEntity: Workflow
            mappedBy: scriptConversion
    manyToOne:
        creator:
            targetEntity: Person  