AppBundle\Entity\WorkflowRun: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        label:
            type: string
        started_at_time:
            type: datetime
        ended_at_time:
            type: datetime
    oneToMany:
        processes_run:
            targetEntity: ProcessRun
            mappedBy: workflow_run
        inputs_run:
            targetEntity: InputRun
            mappedBy: workflow_run
        outputs_run:
            targetEntity: OutputRun
            mappedBy: workflow_run 
    manyToOne:
        workflow:
            targetEntity: Workflow
            inversedBy: workflow_runs