AppBundle\Entity\Workflow: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string
        label:
            type: string
        title:
            type: string
    oneToOne:
        script_conversion:
            targetEntity: ScriptConverter
    oneToMany:
        workflow_runs:
            targetEntity: WorkflowRun
            mappedBy: workflow
        processes:
            targetEntity: Process
            mappedBy: workflow
        inputs:
            targetEntity: Input
            mappedBy: workflow
        outputs:
            targetEntity: Output
            mappedBy: workflow
        quality_annotation:
            targetEntity: QualityAnnotation
            mappedBy: workflow
    manyToOne:
        creator:
            targetEntity: Person  