AppBundle\Entity\WorkflowRun: 
    type: entity
    fields:   
        uri:
            type: string
        label:
            type: string
        started_at_time:
            type: datetime
        ended_at_time:
            type: datetime
    oneToMany:
        processes:
            targetEntity: ProcessRun
            mappedBy: workflow_run
        inputs:
            targetEntity: InputRun
            mappedBy: workflow_run
        outputs:
            targetEntity: OutputRun
            mappedBy: workflow_run 
    manyToOne:
        workflow:
            targetEntity: Workflow
            inversedBy: workflow_runs