AppBundle\Entity\Workflow: 
    type: entity
    fields:   
        description:
            type: string
        label:
            type: string
        title:
            type: string
    oneToMany:
        workflow_runs:
            targetEntity: WorkflowRun
            mappedBy: workflow
        processes:
            targetEntity: Process
            mappedBy: workflow
        inputs:
            targetEntity: Input
            mappedBy: workflow
        outputs:
            targetEntity: Output
            mappedBy: workflow
    manyToOne:
        creator:
            targetEntity: Person            