AppBundle\Entity\WRO: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string
        title:
            type: string
        hash:
            type: string
        created_at:
            type: datetime
    oneToOne:
        workflow:
            targetEntity: Workflow
        script_conversion:
            targetEntity: ScriptConverter
    
    oneToMany:
        resources:
            targetEntity: WROResource
            mappedBy: wro
        annotations:
            targetEntity: WROAnnotation
            mappedBy: wro       
    manyToOne:
        creator:
            targetEntity: Person  