AppBundle\Entity\WROAnnotation: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        description:
            type: string        
        created_at:
            type: datetime
        
    manyToOne:
        resource:
            targetEntity: WROResource
            inversedBy: annotations
        wro:
            targetEntity: WRO
            inversedBy: annotations    
    manyToOne:
        creator:
            targetEntity: Person  