AppBundle\Entity\WROResource: 
    type: entity
    id:
        uri:
            type: string
    fields: 
        type:
            type: string
        created_at:
            type: datetime
        
    manyToOne:
        wro:
            targetEntity: WRO
            invertedBy: resources
    oneToMany:
        annotations:
            targetEntity: WROAnnotation
            mappedBy: resource         